version: "3"

services:
  auth-api:
    build:
      dockerfile: dockerfile
      context: .
    restart: always
    environment:
      FLASK_ENV: production
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
